Fix faulty error output on empty cache (#30)(#37)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -69,30 +69,41 @@ runs:
     - name: Decrypt cached session file
       id: decrypt
       if: ${{ steps.restore-cache.outcome == 'success' }}
-      continue-on-error: true
       shell: bash
       run: |
+        # Default to no session.
+        echo "session_found=false" >> $GITHUB_OUTPUT
 
         # Verify that the encrypted session file was restored from cache.
-        test -s ${{ steps.configure-cache.outputs.path }}
+        if [[ ! -s "${{ steps.configure-cache.outputs.path }}" ]]; then
+          echo "No session file found in cache."
+          exit 0
+        fi
 
         # Decrypt the session file.
         echo "${{ inputs.pantheon-machine-token }}" | \
         openssl enc -d -aes-256-cbc -pbkdf2 -iter 10000 -pass stdin -in ${{ steps.configure-cache.outputs.path }} -out $HOME/.terminus/cache/session
 
-        # Check if restored session is still valid
-        TERMINUS_USER=$(terminus auth:whoami)
+        # Check for restored user (string) or allow command to fail gracefully.
+        TERMINUS_USER=""
+        if ! TERMINUS_USER=$(terminus auth:whoami); then
+          echo "terminus auth:whoami failed."
+          echo "No valid session found."
+          exit 0
+        fi
 
-        if [ -z "$TERMINUS_USER" ]; then
+        # Also assert TERMINUS_USER is a string.
+        if [[ -z "$TERMINUS_USER" ]]; then
           echo "No valid session found. "
-          exit 1
+          exit 0
         fi
 
         echo "Valid session found: $TERMINUS_USER"
+        echo "session_found=true" >> $GITHUB_OUTPUT
 
     - name: Authenticate Terminus
       id: authenticate
-      if: ${{ inputs.pantheon-machine-token && steps.decrypt.outcome != 'success' }}
+      if: ${{ inputs.pantheon-machine-token && steps.decrypt.outputs.session_found != 'true' }}
       shell: bash
       run: |
 
